EXAMPLES = {
    "no_existing_documents": [
        # hotpotqa
            """Existing Documents:\n\nPlan: Question Analysis:
    Identify the Creator: The core component of the question is to identify the individual who created the "Watch Mr. Wizard" television program.
    Obtain Obituary Details: Once the creator is identified, find and retrieve the obituary that was written for this individual.
    Determine the Author of the Obituary: Finally, determine who authored the obituary for the creator of the program.
    Step 1: Retrieve information about `who created the \"Watch Mr. Wizard\" television programming?`.
    Step 2: Identify the creator of the program from the retrieved documents.
    Step 3: Retrieve the information about who wrote the obituary for for the creator.
    Step 4: Determine the author of the obituary.\n\nQuestion: Who wrote the obituary for the man who created the \"Watch Mr. Wizard\" television programming?\n\nThought: The existing documents do not contain any information about the creator of the "Watch Mr. Wizard" television program or the author of the obituary. The plan specifies a step-by-step process to first identify the creator of the program and then find who wrote the obituary for that individual. According to the plan, the first step is to retrieve information about the creator of the television programming. Since we lack this information, we should proceed with this retrieval step.\n\nAction: [Retrieval] Who created the "Watch Mr. Wizard" television programming?""",

            """Existing Documents:\n\nPlan: Key Information Needed:
    Verification if "Games Magazine" was published by "Games Publications."
    Verification if "The General" was published by "Games Publications."
    Step 1: Retrieve Information about `Is Games Magazine published by Games Publications?`, and identify the publisher of Games Magazine.
    Step 2: Retrieve Information about `Is The General published by Games Publications?`, and identify the publisher of The General.
    Step 3: Compare the publishers of both magazines to determine if they were published by Games Publications.\n\nQuestion: Where both Games Magazine and The General published by Games Publications?\n\nThought: The plan outlines the steps needed to verify the publishers of both "Games Magazine" and "The General." The existing documents do not contain information about the publishers of these magazines. According to the plan, the first step involves retrieving information about whether "Games Magazine" is published by "Games Publications." Therefore, the next appropriate action is to write a query for retrieving relevant documents about the publisher of "Games Magazine."\n\nAction: [Retrieval] Is Games Magazine published by Games Publications?""",

        # first step
        """Existing Documents:\n\nPlan: To answer the question, we need to find information about the director of the film 'The Caper of the Golden Bulls.' Then we should determine which nationality is the director born using the retrieval.\nStep 1: Retrieve the relevant documents that mention the film `The Caper of the Golden Bulls.`\nStep 2: Identify the director of the film from the retrieved documents.\nStep 3: Retrieve the relevant information about `Which nationality is the director born?`.\nStep 4: Provide the answer based on the retrieved information.\n\nQuestion: What nationality is the director of film The Caper Of The Golden Bulls?\n\nThought: In our plan, the first step is to identify the director of the film, as this information is crucial for determining the director's nationality. Given our current focus, we need to find documents that mention the film to extract the director's name.\nAction: [Retrieval] Who is the director of the film 'The Caper of the Golden Bulls'?""",  # Russell Rouse
        """Existing Documents:\n\nPlan: I don't have access to personal information about who is the father of Dominic Roco, including his birthday. However, we can retrieve information to answer the question about Dominic Roco's father's birthday.\nSTEP 1: We should retrieve the relevant documents about `Dominic Roco` to identify his father's name.\nSTEP 2: Retrieve the relevant information about the father's birthday.\nSTEP 3: Provide the answer based on the retrieved information.\n\nQuestion: When is Dominic Roco's father's birthday?\n\nThought: There is a plan to retrieve details about Dominic Roco's father firstly, which includes his name. Then we should retrieve his birthday. Given that the specific name of Dominic Roco's father has not yet been obtained, the next step is to gather information about `who is Dominic Roco's father?`. After his name is identified, we can then proceed to find out his birthday.\nAction: [Retrieval] Who is Dominic Roco's father?""", # Bembol Roco
        """Existing Documents:\n\nPlan: To answer the question, we need to find information about `the director of film The Notorious Landlady`. Then, we should retrieve the cause of the director's death.\nSTEP 1: Retrieve the relevant documents about `the director of film The Notorious Landlady`.\nSTEP 2: Identify the director of the film from the retrieved documents.\nSTEP 3: Retrieve the relevant information about `Why did the director die?`.\nSTEP 4: Finish the answer based on the retrieved information.\n\nQuestion: Why did the director of film The Notorious Landlady die?\n\nThought: The existing information clearly indicates that we do not currently know who the director of "The Notorious Landlady" is, which is a prerequisite for answering the question about the cause of their death. The plan specifies retrieving documents about the director as the first step. Since the question cannot be answered without identifying the director first, the next action must focus on retrieving the relevant documents related to this.\nAction: [Retrieval] The director of film The Notorious Landlady.""",  # Richard Quine
        """Existing Documents:\n\nPlan: We know that the film "Magic Mirror" was directed by Manoel de Oliveira. To answer the question, we need to find information about the place of death of Manoel de Oliveira.\nSTEP 1: Retrieve the relevant documents about `Where was the place of death of Manoel de Oliveira?`.\nSTEP 2: Retrieve the place of death of Manoel de Oliveira from the retrieved documents and provide the answer.\n\nQuestion: Where was the place of death of the director of film Magic Mirror (Film)?\n\nThought: In the plan, we have known that the film "Magic Mirror" was directed by Manoel de Oliveira and that we need to find the place of his death. Since the director's identity is already established, the plan outlines specific steps to retrieve relevant documents regarding the place of death of Manoel de Oliveira. Given that this question requires factual data that is not provided in the existing documents, we should proceed with the retrieval step rather than attempt to generate an answer based on insufficient information.\nAction: [Retrieval] Where was the place of death of Manoel de Oliveira?""",

        """Existing Documents:\n\nPlan: We know that the film "Magic Mirror" was directed by Manoel de Oliveira. To answer the question, we need to find information about the place of death of Manoel de Oliveira.\nSTEP 1: Retrieve the relevant documents about `Where was the place of death of Manoel de Oliveira?`.\nSTEP 2: Retrieve the place of death of Manoel de Oliveira from the retrieved documents and provide the answer.\n\nQuestion: Which film was released first, Welcome To Home Gori or Good Sam?\n\nThought: The existing documents do not contain any information about the release dates of the films in question.
The plan outlines a clear step-by-step approach, starting with retrieving information about "Welcome To Home Gori."
Following the plan, we need to begin with STEP 1, which involves using the retrieval system to search for "Welcome To Home Gori" as a film title and find its release date.
Therefore, the next appropriate action is to write a query for retrieving relevant documents about the film "Welcome To Home Gori.".\nAction: [Retrieval] film "Welcome To Home Gori" """,

    ],

    "has_existing_documents": {
        "has_existing_documents": [
        # hotpotqa
        """Existing Documents: Document 1 (Title: Games World of Puzzles): title will remain on the same 9-issue-per-year publication schedule as the original "Games". Games magazine (ISSN 0199-9788) was a magazine devoted to games and puzzles, and is published by Games Publications, a division of Kappa Publishing Group. It was originally published by "Playboy" (debuting with the September/October 1977 issue), then in 1987 was acquired by PSC Limited Partnership for three years and then was briefly out of business in 1990 and 1991 after the PSC owners filed for bankruptcy. The magazine was bought and brought back to life in 1991 by the mail-order company "Bits & Pieces" based in Manhattan.\n\nPlan: Key Information Needed:
Verification if "Games Magazine" was published by "Games Publications."
Verification if "The General" was published by "Games Publications."
Step 1: Retrieve Information about `Is Games Magazine published by Games Publications?`, and identify the publisher of Games Magazine.
Step 2: Retrieve Information about `Is The General published by Games Publications?`, and identify the publisher of The General.
Step 3: Compare the publishers of both magazines to determine if they were published by Games Publications.\n\nQuestion: Where both Games Magazine and The General published by Games Publications?\n\nThought: The existing document provides sufficient information to confirm that "Games Magazine" was published by "Games Publications." However, it does not provide any information about "The General" magazine or its publisher. According to the plan, we need to retrieve additional information to verify whether "The General" was also published by "Games Publications."\n\nAction: [Retrieval] Is The General published by Games Publications?""",

        # second step
        """Existing Documents: Document 1 (Title: The Caper of the Golden Bulls): The Caper of the Golden Bulls The Caper of the Golden Bulls, also known as Carnival of Thieves, is a 1967 film directed by Russell Rouse. It stars Stephen Boyd, Yvette Mimieux, and Giovanna Ralli. During a bombing mission to Germany, wartime pilot Peter Churchman (Boyd) inadvertently destroys a French cathedral. To atone, after the war, Churchman and a crew of accomplices rob a number of banks, making sure the money goes to have the cathedral rebuilt. Churchman moves to Spain, where he opens a successful restaurant. He and another American expatriate, Grace Harvey (Mimieux), are in a romantic relationship.\n\nPlan: To answer the question, we need to find information about the director of the film 'The Caper of the Golden Bulls.' Then we should determine which nationality is the director born using the retrieval.\nStep 1: Retrieve the relevant documents that mention the film `The Caper of the Golden Bulls.`\nStep 2: Identify the director of the film from the retrieved documents.\nStep 3: Retrieve the relevant information about `Which nationality is the director born?`.\nStep 4: Provide the answer based on the retrieved information.\n\nQuestion: What nationality is the director of film The Caper Of The Golden Bulls?\n\nThought: The existing document provides information about the film "The Caper of the Golden Bulls," including its director, Russell Rouse. However, it does not specify his nationality, which is necessary to answer the question. According to the plan, the next action should involve retrieving additional documents that mention Russell Rouse and his nationality.\nAction: [Retrieval] What nationality is the director Russell Rouse born?""",  # American

        """Existing Documents: Document 1 (Title: The Notorious Landlady): The Notorious Landlady The Notorious Landlady is a 1962 comedy/mystery American film starring Kim Novak, Jack Lemmon, and Fred Astaire. The film was directed by Richard Quine, with a script by Blake Edwards and Larry Gelbart. When American diplomat William Gridley (Jack Lemmon) arrives in London, he rents part of Carly Hardwicke\'s (Kim Novak) house from her and promptly begins to fall in love. Gridley doesn\'t know that many people think she killed her British husband, Miles Hardwick (Maxwell Reed), because he has disappeared; but without a body, the police cannot do a thing. Gridley\'s boss is Franklyn Ambruster (Fred\n\nPlan: To answer the question, we need to find information about `the director of film The Notorious Landlady`. Then, we should retrieve the cause of the director's death.\nSTEP 1: Retrieve the relevant documents about `the director of film The Notorious Landlady`.\nSTEP 2: Identify the director of the film from the retrieved documents.\nSTEP 3: Retrieve the relevant information about `Why did the director die?`.\nSTEP 4: Finish the answer based on the retrieved information.\n\nQuestion: Why did the director of film The Notorious Landlady die?\n\nThought: The existing document provides information about the film "The Notorious Landlady" and identifies Richard Quine as its director. However, it does not provide the cause of Richard Quine's death. According to the plan, the next step is to retrieve documents specifically related to the cause of his death, as we lack that information to answer the question.\nAction: [Retrieval] Why did Richard Quine die?""",  # Richard Quine

        """Existing Documents: Document 1 (Title: Happy Ghost III): respectively. The film was followed by "Happy Ghost 4", which was directed by Clifton Ko. Happy Ghost III Happy Ghost III () is a 1986 Hong Kong comedy film directed by Johnnie To. Produced and written by Raymond Wong, the film stars Wong and Maggie Cheung. The film is about a spirit of the late female singer Tsui Pan Han (Maggie Cheung) waits in the afterlife for a chance to be reincarnated. She meets the Godfather (Tsui Hark) who has found an appropriate musical family for her to be reincarnated with. Her opportunity to be born into the new family\n\nPlan: The question is asking about the educational background of the director of the film Happy Ghost IV. The primary piece of information needed is the director's education history, specifically where they studied.\nSTEP 1: Retrieve the name of the director who directed Happy Ghost IV.\nSTEP 2: Once the director is identified, focus on retrieving information related to their academic history.\nSTEP 3: Identify the educational institution where the director studied and provide the answer based on the retrieved information.\n\nQuestion: Where did the director of film Happy Ghost Iv study?\n\nThought: The existing document provides information about "Happy Ghost III" but only briefly mentions "Happy Ghost 4" (IV) as being directed by Clifton Ko.
The question specifically asks about the educational background of the director of "Happy Ghost IV".
The current information is insufficient to answer the question about where the director studied.
Following the plan, we have completed STEP 1 by identifying the director as Clifton Ko.
We now need to proceed with STEP 2 to retrieve information about Clifton Ko's academic history.
Therefore, a retrieval query is necessary to gather more information about Clifton Ko's educational background before we can answer the question.\nAction: [Retrieval] Clifton Ko education background""",  # Richard Quine
        ],
        
        "LLM": [
        # hotpotqa
            """Existing Documents: Document 1 (Title: Watch Mr. Wizard): Watch Mr. Wizard Watch Mr. Wizard is an American television program (1951–1965) for children that demonstrates the science behind ordinary things. The show\'s creator and on-air host was Don Herbert. Marcel LaFollette says of the program, "It enjoyed consistent praise, awards, and high ratings throughout its history. At its peak, "Watch Mr. Wizard" drew audiences in the millions, but its impact was far wider. By 1956, it had prompted the establishment of more than five thousand Mr. Wizard science clubs, with an estimated membership greater than one hundred thousand." It was briefly revived in 1971, and then in the 1980s\n\nDocument 2 (Title: Don Herbert): Don Herbert Donald Jeffry Herbert (born Donald Herbert Kemske and better known as Mr. Wizard, July 10, 1917 – June 12, 2007) was the creator and host of "Watch Mr. Wizard" (1951–65, 1971–72) and of "Mr. Wizard\'s World" (1983–90), which were educational television programs for children devoted to science and technology. He also produced many short video programs about science and authored several popular books about science for children. It was said that no fictional hero was able to rival the popularity and longevity of "the friendly, neighborly scientist". In Herbert\'s obituary, Bill Nye wrote, "Herbert\'s techniques and performances helped\n\nPlan: Question Analysis:
Identify the Creator: The core component of the question is to identify the individual who created the "Watch Mr. Wizard" television program.
Obtain Obituary Details: Once the creator is identified, find and retrieve the obituary that was written for this individual.
Determine the Author of the Obituary: Finally, determine who authored the obituary for the creator of the program.
Step 1: Retrieve information about `who created the \"Watch Mr. Wizard\" television programming?`.
Step 2: Identify the creator of the program from the retrieved documents.
Step 3: Retrieve the information about who wrote the obituary for for the creator.
Step 4: Determine the author of the obituary.\n\nQuestion: Who wrote the obituary for the man who created the \"Watch Mr. Wizard\" television programming?\n\nThought: The existing documents provide sufficient information to answer the question. Document 1 and Document 2 provide details indicating that Don Herbert created "Watch Mr. Wizard." Furthermore, Document 2 mentions that Bill Nye wrote about Herbert in his obituary. According to the plan, the focus was to identify the program's creator, find the obituary, and determine the author. These steps have been completed using the documents available.\n\nAction: [LLM]""",


        """Existing Documents: Document 1 (Title: Games World of Puzzles): title will remain on the same 9-issue-per-year publication schedule as the original "Games". Games magazine (ISSN 0199-9788) was a magazine devoted to games and puzzles, and is published by Games Publications, a division of Kappa Publishing Group. It was originally published by "Playboy" (debuting with the September/October 1977 issue), then in 1987 was acquired by PSC Limited Partnership for three years and then was briefly out of business in 1990 and 1991 after the PSC owners filed for bankruptcy. The magazine was bought and brought back to life in 1991 by the mail-order company "Bits & Pieces" based in Manhattan.\n\nDocument 2 (Title: The General (magazine)): The General (magazine) The General (1964–1998) was a bi-monthly periodical devoted to supporting Avalon Hill\'s line of wargames, with articles on game tactics, history, and industry news. It was the first professionally produced wargaming magazine for the nascent cardboard and hex-map wargaming hobby. Over the years the magazine was variously called "The Avalon Hill General", "Avalon Hill\'s General", "The General Magazine", or simply "General". It was headquartered in Baltimore, Maryland. With the sale of Avalon Hill to Hasbro in 1998 the magazine ceased. Its unofficial heir was "Operations Magazine" published by Multi-Man Publishing to support the line of Avalon Hill\n\nDocument 3 (Title: Avalon Hill): Games released a line of SPI-style games, it met with critical and commercial acclaim. As staff members gradually departed Victory Games for other companies, they were not replaced with new hires. The subsidiary was disbanded in 1989, though existing Victory Games designs were published under that imprint in subsequent years. Avalon Hill also had its own house organ which promoted sale and play of its games, "The General Magazine", which was published regularly between 1964 and 1998. The magazine offered a wide array of features, including articles on both strategies of play and tactics for specific situations, historical analyses, semi-regular\n\nPlan: Question Analysis:
Key Information Needed:
Verification if "Games Magazine" was published by "Games Publications."
Verification if "The General" was published by "Games Publications."
Step 1: Retrieve Information about `Is Games Magazine published by Games Publications?`, and identify the publisher of Games Magazine.
Step 2: Retrieve Information about `Is The General published by Games Publications?`, and identify the publisher of The General.
Step 3: Compare the publishers of both magazines to determine if they were published by Games Publications.\n\nQuestion: Where both Games Magazine and The General published by Games Publications?\n\nThought: The existing documents provide information about both "Games Magazine" and "The General." Document 1 confirms that "Games Magazine" is published by Games Publications. However, documents 2 and 3 clarify that "The General" is associated with Avalon Hill and does not mention Games Publications as its publisher. Based on this information, we can answer the question about the publishers of these magazines without requiring additional retrieval since the plan steps are already covered.\n\nAction: [LLM]""",

        """Existing Documents: Document 1 (Title: Felix Roco): Felix Roco Felix Roco (born 12 April 1989 in Cebu) is a Filipino actor. He is the son of actor Bembol Roco and the twin brother of Dominic Roco. The son of local cinema legend Bembol Roco, 21-year-old Felix Roco made a mark with his internationally acclaimed performance in the Venice Film Festival double-awardee Engkwentro. Taking the lead role of Richard, a gangster running away from the murderous City Death Squad, Felix Roco shows an undeniable range and versatility that may be called one of his most challenging performances ever done. Because Engkwentro was shot a la one continuous take,\n\nDocument 2 (Title: Bembol Roco): Bembol Roco Rafael Aranda Roco Jr. (born November 20, 1953) is a Filipino actor whose work ranges from films to television. He is famous for his critically acclaimed role as Julio Madiaga in "" ("Manila in the Claws Of Light"). Though he acts in his country\'s films, he also had an important role in the 1982 Australian-U.S. film "The Year of Living Dangerously". He also portrayed bald villain roles in Philippine action movies as well as various supporting roles. Bem currently stars in Sine Novela: Tinik Sa Dibdib. He has twin sons named Felix and Dominic. A recurring theme in\n\nPlan: I don't have access to personal information about who is the father of Dominic Roco, including his birthday. However, we can retrieve information to answer the question about Dominic Roco's father's birthday.\nSTEP 1: We should retrieve the relevant documents about `Dominic Roco` to identify his father's name.\nSTEP 2: Retrieve the relevant information about the father's birthday.\nSTEP 3: Provide the answer based on the retrieved information.\n\nQuestion: When is Dominic Roco's father's birthday?\n\nThought: The existing documents provide information about both Felix Roco, Dominic Roco and Bembol Roco, indicating that Bembol Roco is the father of Felix and Dominic Roco. Document 1 mentions Dominic Roco's father is Bembol Roco, which aligns with STEP 1 of the plan. Document 2 mentions Bembol Roco's birthday, which is necessary to answer the question regarding Dominic Roco's father's birthday (STEP 2). Based on the plan, we already have sufficient information to answer the question about Dominic Roco's father's birthday.\nAction: [LLM]""", # November 20, 1953

        """Existing Documents: Document 1 (Title: Manoel de Oliveira): failure. Oliveira died in Porto on 2 April 2015, aged 106. He was survived by a wife, four children, and numerous grandchildren and great-grandchildren. Manoel de Oliveira Manoel Cândido Pinto de Oliveira GCSE, GCIH (; 11 December 1908 – 2 April 2015) was a Portuguese film director and screenwriter born in Cedofeita, Porto. He first began making films in 1927, when he and some friends attempted to make a film about World War I. In 1931 he completed his first film "Douro, Faina Fluvial", a documentary about his home city Porto made in the city symphony genre. He made his\n\nPlan: We know that the film "Magic Mirror" was directed by Manoel de Oliveira. To answer the question, we need to find information about the place of death of Manoel de Oliveira.\nSTEP 1: Retrieve the relevant documents about `Where was the place of death of Manoel de Oliveira?`.\nSTEP 2: Retrieve the place of death of Manoel de Oliveira from the retrieved documents and provide the answer.\n\nQuestion: Where was the place of death of the director of film Magic Mirror (Film)?\n\nThought: The existing document does state that Manoel de Oliveira died in Porto. Therefore, the document provides sufficient information to answer the question. Since all necessary details about his place of death are already present in the provided documents, we can proceed to generate a comprehensive answer.\nAction: [LLM]""",  # Porto


        # step 3
        """Existing Documents: Document 1 (Title: The Caper of the Golden Bulls): The Caper of the Golden Bulls The Caper of the Golden Bulls, also known as Carnival of Thieves, is a 1967 film directed by Russell Rouse. It stars Stephen Boyd, Yvette Mimieux, and Giovanna Ralli. During a bombing mission to Germany, wartime pilot Peter Churchman (Boyd) inadvertently destroys a French cathedral. To atone, after the war, Churchman and a crew of accomplices rob a number of banks, making sure the money goes to have the cathedral rebuilt. Churchman moves to Spain, where he opens a successful restaurant. He and another American expatriate, Grace Harvey (Mimieux), are in a romantic relationship.\n\nDocument 2 (Title: Russell Rouse): Russell Rouse Russell Rouse (November 20, 1913 – October 2, 1987) was an American screenwriter, director, and producer who is noted for the "offbeat creativity and originality" of his screenplays and for film noir movies and television episodes produced in the 1950s. Rouse was the son of film pioneer Edwin Russell; his great uncle was the 1920s actor William Russell. He was educated at UCLA. His first employment in films was in the prop department at Paramount Studios, where he began writing screenplays. His play, "Yokel Boy", was filmed in 1942 and became his first film writing credit. Rouse has\n\nPlan: To answer the question, we need to find information about the director of the film 'The Caper of the Golden Bulls.' Then we should determine which nationality is the director born using the retrieval.\nStep 1: Retrieve the relevant documents that mention the film `The Caper of the Golden Bulls.`\nStep 2: Identify the director of the film from the retrieved documents.\nStep 3: Retrieve the relevant information about `Which nationality is the director born?`.\nStep 4: Provide the answer based on the retrieved information.\n\nQuestion: What nationality is the director of film The Caper Of The Golden Bulls?\n\nThought: Looking through the existing documents, Document 1 clearly states that Russell Rouse is the director of the film. Document 2 provides additional context about Russell Rouse's background, including that he was an American screenwriter, director, and producer. This suggests that his nationality is American. These information directly answers the question about the director’s nationality. Therefore, I do not need to retrieve additional documents.\nAction: [LLM]""",  # American

        """Existing Documents: Document 1 (Title: The Notorious Landlady): The Notorious Landlady The Notorious Landlady is a 1962 comedy/mystery American film starring Kim Novak, Jack Lemmon, and Fred Astaire. The film was directed by Richard Quine, with a script by Blake Edwards and Larry Gelbart. When American diplomat William Gridley (Jack Lemmon) arrives in London, he rents part of Carly Hardwicke\'s (Kim Novak) house from her and promptly begins to fall in love. Gridley doesn\'t know that many people think she killed her British husband, Miles Hardwick (Maxwell Reed), because he has disappeared; but without a body, the police cannot do a thing. Gridley\'s boss is Franklyn Ambruster (Fred\n\nDocument 2 (Title: Richard Quine): "The Prisoner of Zenda" (1979). Depressed over poor health, Quine died of a self-inflicted gunshot wound in June 1989 at the age of 68. Born in Detroit, Quine\'s father was an actor. Quine\'s family moved to Los Angeles when he was six years old. As a child, he began working as a radio actor and became a minor radio star. He then appeared in vaudeville before moving on to stage roles. Quine made his film debut in the drama "Cavalcade" (1933). He could also be seen in "The World Changes" (1933) (alongside a young Mickey Rooney), "Counsellor-at-Law" (1933), "Jane Eyre"\n\nPlan: To answer the question, we need to find information about `the director of film The Notorious Landlady`. Then, we should retrieve the cause of the director's death.\nSTEP 1: Retrieve the relevant documents about `the director of film The Notorious Landlady`.\nSTEP 2: Identify the director of the film from the retrieved documents.\nSTEP 3: Retrieve the relevant information about `Why did the director die?`.\nSTEP 4: Finish the answer based on the retrieved information.\n\nQuestion: Why did the director of film The Notorious Landlady die?\n\nThought: In existing documents, Document 1 mentions Richard Quine as the director of "The Notorious Landlady", while Document 2 specifically addresses Richard Quine's death, stating that he died from a self-inflicted gunshot wound due to depression over poor health. Therefore, we have successfully gathered the relevant information. The existing documents are sufficient to answer the question about the director's cause of death.\nAction: [LLM]""",  # Richard Quine


    ],
    },

    "LLM": [
        # hotpotqa
            """Existing Documents: Document 1 (Title: Watch Mr. Wizard): Watch Mr. Wizard Watch Mr. Wizard is an American television program (1951–1965) for children that demonstrates the science behind ordinary things. The show\'s creator and on-air host was Don Herbert. Marcel LaFollette says of the program, "It enjoyed consistent praise, awards, and high ratings throughout its history. At its peak, "Watch Mr. Wizard" drew audiences in the millions, but its impact was far wider. By 1956, it had prompted the establishment of more than five thousand Mr. Wizard science clubs, with an estimated membership greater than one hundred thousand." It was briefly revived in 1971, and then in the 1980s\n\nDocument 2 (Title: Don Herbert): Don Herbert Donald Jeffry Herbert (born Donald Herbert Kemske and better known as Mr. Wizard, July 10, 1917 – June 12, 2007) was the creator and host of "Watch Mr. Wizard" (1951–65, 1971–72) and of "Mr. Wizard\'s World" (1983–90), which were educational television programs for children devoted to science and technology. He also produced many short video programs about science and authored several popular books about science for children. It was said that no fictional hero was able to rival the popularity and longevity of "the friendly, neighborly scientist". In Herbert\'s obituary, Bill Nye wrote, "Herbert\'s techniques and performances helped\n\nPlan: Question Analysis:
Identify the Creator: The core component of the question is to identify the individual who created the "Watch Mr. Wizard" television program.
Obtain Obituary Details: Once the creator is identified, find and retrieve the obituary that was written for this individual.
Determine the Author of the Obituary: Finally, determine who authored the obituary for the creator of the program.
Step 1: Retrieve information about `who created the \"Watch Mr. Wizard\" television programming?`.
Step 2: Identify the creator of the program from the retrieved documents.
Step 3: Retrieve the information about who wrote the obituary for for the creator.
Step 4: Determine the author of the obituary.\n\nQuestion: Who wrote the obituary for the man who created the \"Watch Mr. Wizard\" television programming?\n\nThought: The existing documents provide sufficient information to answer the question. Document 1 and Document 2 provide details indicating that Don Herbert created "Watch Mr. Wizard." Furthermore, Document 2 mentions that Bill Nye wrote about Herbert in his obituary. According to the plan, the focus was to identify the program's creator, find the obituary, and determine the author. These steps have been completed using the documents available.\n\nAction: [LLM]""",


        """Existing Documents: Document 1 (Title: Games World of Puzzles): title will remain on the same 9-issue-per-year publication schedule as the original "Games". Games magazine (ISSN 0199-9788) was a magazine devoted to games and puzzles, and is published by Games Publications, a division of Kappa Publishing Group. It was originally published by "Playboy" (debuting with the September/October 1977 issue), then in 1987 was acquired by PSC Limited Partnership for three years and then was briefly out of business in 1990 and 1991 after the PSC owners filed for bankruptcy. The magazine was bought and brought back to life in 1991 by the mail-order company "Bits & Pieces" based in Manhattan.\n\nDocument 2 (Title: The General (magazine)): The General (magazine) The General (1964–1998) was a bi-monthly periodical devoted to supporting Avalon Hill\'s line of wargames, with articles on game tactics, history, and industry news. It was the first professionally produced wargaming magazine for the nascent cardboard and hex-map wargaming hobby. Over the years the magazine was variously called "The Avalon Hill General", "Avalon Hill\'s General", "The General Magazine", or simply "General". It was headquartered in Baltimore, Maryland. With the sale of Avalon Hill to Hasbro in 1998 the magazine ceased. Its unofficial heir was "Operations Magazine" published by Multi-Man Publishing to support the line of Avalon Hill\n\nDocument 3 (Title: Avalon Hill): Games released a line of SPI-style games, it met with critical and commercial acclaim. As staff members gradually departed Victory Games for other companies, they were not replaced with new hires. The subsidiary was disbanded in 1989, though existing Victory Games designs were published under that imprint in subsequent years. Avalon Hill also had its own house organ which promoted sale and play of its games, "The General Magazine", which was published regularly between 1964 and 1998. The magazine offered a wide array of features, including articles on both strategies of play and tactics for specific situations, historical analyses, semi-regular\n\nPlan: Question Analysis:
Key Information Needed:
Verification if "Games Magazine" was published by "Games Publications."
Verification if "The General" was published by "Games Publications."
Step 1: Retrieve Information about `Is Games Magazine published by Games Publications?`, and identify the publisher of Games Magazine.
Step 2: Retrieve Information about `Is The General published by Games Publications?`, and identify the publisher of The General.
Step 3: Compare the publishers of both magazines to determine if they were published by Games Publications.\n\nQuestion: Where both Games Magazine and The General published by Games Publications?\n\nThought: The existing documents provide information about both "Games Magazine" and "The General." Document 1 confirms that "Games Magazine" is published by Games Publications. However, documents 2 and 3 clarify that "The General" is associated with Avalon Hill and does not mention Games Publications as its publisher. Based on this information, we can answer the question about the publishers of these magazines without requiring additional retrieval since the plan steps are already covered.\n\nAction: [LLM]""",

        """Existing Documents: Document 1 (Title: Felix Roco): Felix Roco Felix Roco (born 12 April 1989 in Cebu) is a Filipino actor. He is the son of actor Bembol Roco and the twin brother of Dominic Roco. The son of local cinema legend Bembol Roco, 21-year-old Felix Roco made a mark with his internationally acclaimed performance in the Venice Film Festival double-awardee Engkwentro. Taking the lead role of Richard, a gangster running away from the murderous City Death Squad, Felix Roco shows an undeniable range and versatility that may be called one of his most challenging performances ever done. Because Engkwentro was shot a la one continuous take,\n\nDocument 2 (Title: Bembol Roco): Bembol Roco Rafael Aranda Roco Jr. (born November 20, 1953) is a Filipino actor whose work ranges from films to television. He is famous for his critically acclaimed role as Julio Madiaga in "" ("Manila in the Claws Of Light"). Though he acts in his country\'s films, he also had an important role in the 1982 Australian-U.S. film "The Year of Living Dangerously". He also portrayed bald villain roles in Philippine action movies as well as various supporting roles. Bem currently stars in Sine Novela: Tinik Sa Dibdib. He has twin sons named Felix and Dominic. A recurring theme in\n\nPlan: I don't have access to personal information about who is the father of Dominic Roco, including his birthday. However, we can retrieve information to answer the question about Dominic Roco's father's birthday.\nSTEP 1: We should retrieve the relevant documents about `Dominic Roco` to identify his father's name.\nSTEP 2: Retrieve the relevant information about the father's birthday.\nSTEP 3: Provide the answer based on the retrieved information.\n\nQuestion: When is Dominic Roco's father's birthday?\n\nThought: The existing documents provide information about both Felix Roco, Dominic Roco and Bembol Roco, indicating that Bembol Roco is the father of Felix and Dominic Roco. Document 1 mentions Dominic Roco's father is Bembol Roco, which aligns with STEP 1 of the plan. Document 2 mentions Bembol Roco's birthday, which is necessary to answer the question regarding Dominic Roco's father's birthday (STEP 2). Based on the plan, we already have sufficient information to answer the question about Dominic Roco's father's birthday.\nAction: [LLM]""", # November 20, 1953

        """Existing Documents: Document 1 (Title: Manoel de Oliveira): failure. Oliveira died in Porto on 2 April 2015, aged 106. He was survived by a wife, four children, and numerous grandchildren and great-grandchildren. Manoel de Oliveira Manoel Cândido Pinto de Oliveira GCSE, GCIH (; 11 December 1908 – 2 April 2015) was a Portuguese film director and screenwriter born in Cedofeita, Porto. He first began making films in 1927, when he and some friends attempted to make a film about World War I. In 1931 he completed his first film "Douro, Faina Fluvial", a documentary about his home city Porto made in the city symphony genre. He made his\n\nPlan: We know that the film "Magic Mirror" was directed by Manoel de Oliveira. To answer the question, we need to find information about the place of death of Manoel de Oliveira.\nSTEP 1: Retrieve the relevant documents about `Where was the place of death of Manoel de Oliveira?`.\nSTEP 2: Retrieve the place of death of Manoel de Oliveira from the retrieved documents and provide the answer.\n\nQuestion: Where was the place of death of the director of film Magic Mirror (Film)?\n\nThought: The existing document does state that Manoel de Oliveira died in Porto. Therefore, the document provides sufficient information to answer the question. Since all necessary details about his place of death are already present in the provided documents, we can proceed to generate a comprehensive answer.\nAction: [LLM]""",  # Porto


        # step 3
        """Existing Documents: Document 1 (Title: The Caper of the Golden Bulls): The Caper of the Golden Bulls The Caper of the Golden Bulls, also known as Carnival of Thieves, is a 1967 film directed by Russell Rouse. It stars Stephen Boyd, Yvette Mimieux, and Giovanna Ralli. During a bombing mission to Germany, wartime pilot Peter Churchman (Boyd) inadvertently destroys a French cathedral. To atone, after the war, Churchman and a crew of accomplices rob a number of banks, making sure the money goes to have the cathedral rebuilt. Churchman moves to Spain, where he opens a successful restaurant. He and another American expatriate, Grace Harvey (Mimieux), are in a romantic relationship.\n\nDocument 2 (Title: Russell Rouse): Russell Rouse Russell Rouse (November 20, 1913 – October 2, 1987) was an American screenwriter, director, and producer who is noted for the "offbeat creativity and originality" of his screenplays and for film noir movies and television episodes produced in the 1950s. Rouse was the son of film pioneer Edwin Russell; his great uncle was the 1920s actor William Russell. He was educated at UCLA. His first employment in films was in the prop department at Paramount Studios, where he began writing screenplays. His play, "Yokel Boy", was filmed in 1942 and became his first film writing credit. Rouse has\n\nPlan: To answer the question, we need to find information about the director of the film 'The Caper of the Golden Bulls.' Then we should determine which nationality is the director born using the retrieval.\nStep 1: Retrieve the relevant documents that mention the film `The Caper of the Golden Bulls.`\nStep 2: Identify the director of the film from the retrieved documents.\nStep 3: Retrieve the relevant information about `Which nationality is the director born?`.\nStep 4: Provide the answer based on the retrieved information.\n\nQuestion: What nationality is the director of film The Caper Of The Golden Bulls?\n\nThought: Looking through the existing documents, Document 1 clearly states that Russell Rouse is the director of the film. Document 2 provides additional context about Russell Rouse's background, including that he was an American screenwriter, director, and producer. This suggests that his nationality is American. These information directly answers the question about the director’s nationality. Therefore, I do not need to retrieve additional documents.\nAction: [LLM]""",  # American

        """Existing Documents: Document 1 (Title: The Notorious Landlady): The Notorious Landlady The Notorious Landlady is a 1962 comedy/mystery American film starring Kim Novak, Jack Lemmon, and Fred Astaire. The film was directed by Richard Quine, with a script by Blake Edwards and Larry Gelbart. When American diplomat William Gridley (Jack Lemmon) arrives in London, he rents part of Carly Hardwicke\'s (Kim Novak) house from her and promptly begins to fall in love. Gridley doesn\'t know that many people think she killed her British husband, Miles Hardwick (Maxwell Reed), because he has disappeared; but without a body, the police cannot do a thing. Gridley\'s boss is Franklyn Ambruster (Fred\n\nDocument 2 (Title: Richard Quine): "The Prisoner of Zenda" (1979). Depressed over poor health, Quine died of a self-inflicted gunshot wound in June 1989 at the age of 68. Born in Detroit, Quine\'s father was an actor. Quine\'s family moved to Los Angeles when he was six years old. As a child, he began working as a radio actor and became a minor radio star. He then appeared in vaudeville before moving on to stage roles. Quine made his film debut in the drama "Cavalcade" (1933). He could also be seen in "The World Changes" (1933) (alongside a young Mickey Rooney), "Counsellor-at-Law" (1933), "Jane Eyre"\n\nPlan: To answer the question, we need to find information about `the director of film The Notorious Landlady`. Then, we should retrieve the cause of the director's death.\nSTEP 1: Retrieve the relevant documents about `the director of film The Notorious Landlady`.\nSTEP 2: Identify the director of the film from the retrieved documents.\nSTEP 3: Retrieve the relevant information about `Why did the director die?`.\nSTEP 4: Finish the answer based on the retrieved information.\n\nQuestion: Why did the director of film The Notorious Landlady die?\n\nThought: In existing documents, Document 1 mentions Richard Quine as the director of "The Notorious Landlady", while Document 2 specifically addresses Richard Quine's death, stating that he died from a self-inflicted gunshot wound due to depression over poor health. Therefore, we have successfully gathered the relevant information. The existing documents are sufficient to answer the question about the director's cause of death.\nAction: [LLM]""",  # Richard Quine

    ]
}